version: '3'

services:
  backend:
    build: ./real_estate_ai
    ports:
      - "8000:8000"
    env_file:
      - ./real_estate_ai/.env

  frontend:
    build: ./real-estate-ai-frontend
    ports:
      - "5173:5173"
    depends_on:
      - backend
      